#!/usr/bin/zsh

randbg="$(ls -d $HOME/Pictures/Backgrounds/* | sort -R | sed 1q)"
bgpath=${1:-$randbg}

nitrogen --set-scaled --save "$bgpath"
$GOPATH/bin/schemer2 --format img::urxvt -in "$bgpath" -out $HOME/.Xresources

xrdb -merge $HOME/.Xresources
